AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  bitbank-transactions

  Sample SAM Template for bitbank-transactions

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  # Order
  MarketOrderFunctionXrp:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello-world/
      Handler: app.marketOrderHandler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      Events:
        CloudWatchEvent:
          Type: Schedule
          Properties:
            Schedule: cron(0 0 * * ? *)
      MemorySize: 128
      Timeout: 100
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonS3FullAccess
        - SecretsManagerReadWrite
      Environment:
        Variables:
          JPY_BUDGET: "1000"
          PAIR: "xrp_jpy"
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - app.ts

  MarketOrderFunctionEth:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello-world/
      Handler: app.marketOrderHandler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      Events:
        CloudWatchEvent:
          Type: Schedule
          Properties:
            Schedule: cron(1 0 * * ? *)
      Timeout: 100
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonS3FullAccess
        - SecretsManagerReadWrite
      Environment:
        Variables:
          JPY_BUDGET: "2000"
          PAIR: "eth_jpy"
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - app.ts

  MarketOrderFunctionAvax:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello-world/
      Handler: app.marketOrderHandler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      Events:
        CloudWatchEvent:
          Type: Schedule
          Properties:
            Schedule: cron(2 0 * * ? *)
      MemorySize: 128
      Timeout: 100
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonS3FullAccess
        - SecretsManagerReadWrite
      Environment:
        Variables:
          JPY_BUDGET: "2000"
          PAIR: "avax_jpy"
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - app.ts

  MarketOrderFunctionBtc:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello-world/
      Handler: app.marketOrderHandler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      Events:
        CloudWatchEvent:
          Type: Schedule
          Properties:
            Schedule: cron(2 0 * * ? *)
      MemorySize: 128
      Timeout: 100
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonS3FullAccess
        - SecretsManagerReadWrite
      Environment:
        Variables:
          JPY_BUDGET: "1000"
          PAIR: "btc_jpy"
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - app.ts
  # # Withdrawal
  # WithdrawalFunction:
  #   Type: AWS::Serverless::Function
  #   Properties:
  #     CodeUri: hello-world/
  #     Handler: app.withdrawalHandler
  #     Runtime: nodejs20.x
  #     Architectures:
  #       - x86_64
  #     Events:
  #       CloudWatchEvent:
  #         Type: Schedule
  #         Properties:
  #           Schedule: cron(0 1 * * ? *)
  #     MemorySize: 128
  #     Timeout: 100
  #     Policies:
  #       - AWSLambdaBasicExecutionRole
  #       - AmazonS3FullAccess
  #       - SecretsManagerReadWrite
  #     Environment:
  #       Variables:
  #         AMOUNT: "0.1"
  #   Metadata: # Manage esbuild properties
  #     BuildMethod: esbuild
  #     BuildProperties:
  #       Minify: true
  #       Target: "es2020"
  #       Sourcemap: true
  #       EntryPoints:
  #         - app.ts
  SlackNotifierFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello-world/
      Handler: app.slackNotifierHandler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      Events:
        DailyTrigger:
          Type: Schedule
          Properties:
            Schedule: cron(0 1 * * ? *) # Runs daily at 1:00 AM UTC
      MemorySize: 128
      Timeout: 100
      Policies:
        - AWSLambdaBasicExecutionRole
        - SecretsManagerReadWrite
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - app.ts
